version: "3.9"
services:
  backend:
    build: ./SampleWebApiAspNetCore/
#    ports:
#      - "5000:5000"
  frontend:
    build: ./nginx/
#    image: nginx:alpine
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "443:443"
