version: 2.1
orbs:
#  heroku: circleci/heroku@1.2.6
  windows: circleci/windows@2.4.1
jobs:
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "SampleWebApiAspNetCore/SampleWebApiAspNetCore.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release
#      - run:
#          name: Creating Artifacts
#          command: |
#             ls;
#             mkdir /tmp/artifacts;
#             cp . /tmp/artifacts;
#            echo "my artifact file" > /tmp/art-1;
#            mkdir /tmp/artifacts;
#            echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - store_artifacts:
          path: SampleWebApiAspNetCore\bin\Release\net5.0\
#          destination: artifact-file0
#      - store_artifacts:
#          path: /tmp/artifacts/art-2
#          destanation: artifact-file1