version: 2.1
orbs:
#  heroku: circleci/heroku@1.2.6
  windows: circleci/windows@2.4.1
jobs:
  build-artifact:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "SampleWebApiAspNetCore/SampleWebApiAspNetCore.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release
      - run:
          name: Creating Artifacts
          command: |
              powershell Compress-Archive SampleWebApiAspNetCore\bin\Release\net5.0\ artifact-net5.0-rel-bin.zip
              ls
#             mkdir /tmp/artifacts;
#             cp . /tmp/artifacts;
#            echo "my artifact file" > /tmp/art-1;
#            mkdir /tmp/artifacts;
#            echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - store_artifacts:
          path: artifact-net5.0-rel-bin.zip
#          destination: net5.0-compile-app
#      - store_artifacts:
#          path: /tmp/artifacts/art-2
#          destanation: artifact-file1

  build-images:
    environment:
      F_IMAGE_NAME: jncnjq/aspnetingress
      B_IMAGE_NAME: jncnjq/aspnetapp
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Dockers images
          command: |
              ls
              cd SampleWebApiAspNetCore
              docker build -t $B_IMAGE_NAME .
              cd ../nginx
              docker build -t $F_IMAGE_NAME .

workflows:
  version: 2
  build-master:
    jobs:
      - build-artifact:
          filters:
            branches:
              only: main
      - build-images:
          filters:
            branches:
              only: main