# This is a basic workflow to help you get started with Actions
# This is a basic workflow to help you get started with Actions
name: CI-CD-To-AWS-EC2
# Controls when the workflow will run
on:
  push:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-remote-docker:
    name: Deploy to remote docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker container stop $(docker ps -aq)
            docker rm $(docker container ls -aq)
            docker rmi $(docker image ls)
            cd ~/ASPNETCore-WebAPI-Sample
            git pull
            docker compose up -d
            exit
  deploy-aws:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          password: ${{ secrets.AWS_PASSWORD }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            docker container stop $(docker ps -aq)
            docker rm $(docker container ls -aq)
            docker rmi $(docker image ls)
            cd ~/ASPNETCore-WebAPI-Sample
            git pull
            docker compose up -d
            exit
